---
functional:
  - Сайт позволяет игрокам соревноваться друг с другом в решении задач
  - Сайт позволяет видеть написание кода друг у друга
  - Сайт позволяет создавать собственные игры
  - Сайт позволяет соревноваться с ботом
  - Сайт позволяет выбирать сложность задания
  - Сайт позволяет выбирать язык программирования для решения задачи
  - Сайт позволяет выбирать тематику задания
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт позволяет регистрироваться с помощью Github и Discord
implicit:
  - Сайт представляет собой open-source проект с возможностью внесения изменений
  - Сайт поддерживает систему рейтинга всех участников
  - Сайт имеет чат со всеми участниками сообщества
